### ISSUE TITLE
Project-XLua示例代码连接服务器时Unity卡死

### ISSUE THREAD

**Issue by chardian** [gmhevinci/MotionFramework-Projects#1]
Editor.log卡死时的报错如下

========== OUTPUTTING STACK TRACE ==================

0x00007FFBD18AA839 (KERNELBASE) RaiseException
0x00007FFB7BD96025 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\utils\mono-log-common.c:142] mono_log_write_logfile 
0x00007FFB7BD84D41 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\eglib\goutput.c:131] monoeg_g_log 
0x00007FFB7BE5ED62 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\threadpool-io.c:533] wakeup_pipes_init 
0x00007FFB7BE5D419 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\threadpool-io.c:575] initialize 
0x00007FFB7BE5E7B0 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\threadpool-io.c:616] ves_icall_System_IOSelector_Add 
0x000001759D7AC08D (Mono JIT Code) (wrapper managed-to-native) System.IOSelector:Add (intptr,System.IOSelectorJob)
0x000001759D7AB3E3 (Mono JIT Code) System.Net.Sockets.Socket:BeginSConnect (System.Net.Sockets.SocketAsyncResult)
0x000001759D7AADFB (Mono JIT Code) System.Net.Sockets.Socket:BeginConnect (System.Net.EndPoint,System.AsyncCallback,object)
0x000001759D7AA1FB (Mono JIT Code) System.Net.Sockets.Socket:ConnectAsync (System.Net.Sockets.SocketAsyncEventArgs)
0x000001759D7A9ECB (Mono JIT Code) [E:\work\Client\demo_core\Project-XLua\Assets\MotionFramework\Scripts\Runtime\Engine\Engine.Network\Socket\TCP\TcpClient.cs:114] MotionFramework.Network.TcpClient:ConnectAsync (System.Net.IPEndPoint,System.Action`1<System.Net.Sockets.SocketError>) 
0x000001759D7A8B4B (Mono JIT Code) [E:\work\Client\demo_core\Project-XLua\Assets\MotionFramework\Scripts\Runtime\Module\Module.Network\NetworkManager.cs:123] MotionFramework.Network.NetworkManager:ConnectServer (string,int) 
0x000001759D7A87DB (Mono JIT Code) NetworkManagerWrap101:ConnectServer107 (intptr)
0x000001759D77CCEB (Mono JIT Code) (wrapper native-to-managed) NetworkManagerWrap101:ConnectServer107 (intptr)
0x00007FFB8AF710CC (xlua) cls_newindexer
0x00007FFB8AF47C92 (xlua) lua_setlocal

服务器是pyhton随便写的一个,大概跟这个没关, 代码如下
``` python
import socket

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
host = '127.0.0.1'
port = 10002

s.bind((host, port))

s.listen(5)
while True:
    c, addr = s.accept()
    print('连接成功了', addr)
```

客户端调用连接之后,服务端打印出了"连接成功了",  然后Unity卡死

**Comment by chardian** [comment]
好吧, 是win10防火墙的问题, 全关掉就好了. 我tm服了

**Comment by gmhevinci** [comment]
欢迎你进MotionFramework的QQ群：654986302
有问题可以第一时间反馈。
